server {
    listen 80;
    server_name localhost;

    # Xử lý đường dẫn /api (Có hoặc không có dấu / ở cuối)
    location /api {
        alias /usr/share/nginx/html/; 
        index index.html;
        default_type application/json;
        # Dòng này quan trọng: Nếu không tìm thấy file tên là api, hãy trả về index.html
        try_files $uri $uri/ /index.html; 
    }

    # Đường dẫn gốc
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        default_type application/json;
    }
}